const { chromium, ok, newPhone, settle, txt, state, decode, summary, shotPath, DEMO_URL, DEMO_FILE_URL } = require('./lib.js');
const SHOT = n => shotPath('auto', n);
(async () => {
  const b = await chromium.launch();
  const { ctx, p, wa, errs } = await newPhone(b);
  const primary = '.q-foot .q-primary';
  const count = () => txt(p, '.q-count');
  const title = () => txt(p, '#q-title');

  console.log('INTRO');
  await p.tap('.app-cta[data-form="auto"]'); await settle(p);
  ok(await p.isVisible('.q-flow'), 'flow opens full-screen');
  ok(await title() === 'Cotiza tu seguro de auto', 'intro title', await title());
  ok((await state(p))?.view === 'intro' && (await state(p)).i === 1, 'history entry for intro', await state(p));
  ok(await p.evaluate(() => document.getElementById('content-app').inert), 'page behind is inert');
  ok(await p.evaluate(() => document.activeElement.id) === 'q-title', 'focus on the screen title');
  ok((await txt(p, '.q-have')).includes('Año, marca y modelo del auto'), 'have-ready checklist');
  ok(!(await p.isVisible('.q-secondary')), 'no resume button on a fresh start');
  await p.screenshot({ path: SHOT('0-intro') });

  console.log('INTRO ZIP');
  await p.tap(primary); await settle(p);
  ok((await state(p))?.view === 'intro' && (await txt(p, '#q-intro-zip-err')).includes('ZIP'), 'Empezar asks for the ZIP first', await txt(p, '#q-intro-zip-err'));
  ok(await p.evaluate(() => document.activeElement.id) === 'q-intro-zip', 'focus moves to the ZIP');
  await p.type('#q-intro-zip', '33a1-30'); await settle(p);
  ok(await p.inputValue('#q-intro-zip') === '33130' && await txt(p, '#q-intro-zip-err') === '', 'intro ZIP keeps digits; error clears', await p.inputValue('#q-intro-zip'));

  console.log('STEP 1 vehículo');
  await p.tap(primary); await settle(p);
  ok(await txt(p, '.q-zip-pill') === '33130', 'ZIP pill on the first question', await txt(p, '.q-zip-pill'));
  ok(await title() === '¿Qué auto quieres asegurar?', 'vehicle title');
  ok(await count() === 'Paso 1 de 9', 'progress Paso 1 de 9', await count());
  ok(await p.getAttribute(primary, 'class').then(c => c.includes('is-incomplete')), 'Continuar looks incomplete');
  await p.screenshot({ path: SHOT('1-vehiculo-empty') });
  await p.tap(primary); await settle(p);
  const e1 = await p.$$eval('.q-error', n => n.map(x => x.textContent).filter(Boolean));
  ok(e1.includes('Elige el año.') && e1.includes('Elige la marca y el modelo.'), 'required errors shown', e1);
  ok(await p.evaluate(() => document.activeElement.id) === 'q-anio', 'focus moves to the first problem');
  ok(await title() === '¿Qué auto quieres asegurar?', 'did not advance');
  await p.tap('#q-anio'); await settle(p);
  ok(await txt(p, '#sheet-title') === 'Año del vehículo', 'year sheet opens');
  ok((await state(p)).sheet === true, 'picker has its own history entry');
  await p.tap('.sheet-row:has-text("2021")'); await settle(p);
  ok(await txt(p, '#sheet-title') === 'Marca', 'year pick flows straight into Marca');
  await p.screenshot({ path: SHOT('1b-marcas') });
  await p.tap('.make-tile:has-text("Honda")'); await settle(p);
  ok(await txt(p, '#sheet-title') === 'Modelos Honda', 'models of Honda');
  await p.tap('.sheet-row:has-text("CR-V")'); await settle(p);
  ok(!(await p.$('.sheet')), 'sheet closed after model pick');
  ok(!(await state(p)).sheet, 'picker history entry dropped', await state(p));
  ok(await txt(p, '#q-anio') === '2021' && (await txt(p, '#q-vehiculo')).startsWith('CR-V'), 'rows show 2021 / CR-V Honda', [await txt(p, '#q-anio'), await txt(p, '#q-vehiculo')]);
  ok((await p.$$eval('.q-error', n => n.map(x => x.textContent).filter(Boolean))).length === 0, 'errors cleared once answered');
  // VIN: typo shown on blur, fixed live, uppercase
  await p.fill('#q-vin', 'abc'); await p.tap('#q-title'); await settle(p);
  ok((await txt(p, '#q-vin-err')).startsWith('El VIN tiene 17'), 'bad VIN flagged on blur', await txt(p, '#q-vin-err'));
  await p.fill('#q-vin', ''); await p.type('#q-vin', '1hgcm82633a004352'); await settle(p);
  ok(await p.inputValue('#q-vin') === '1HGCM82633A004352', 'VIN uppercased as typed', await p.inputValue('#q-vin'));
  ok(await txt(p, '#q-vin-err') === '', 'VIN error cleared when valid');
  ok(!(await p.getAttribute(primary, 'class')).includes('is-incomplete'), 'Continuar turns yellow when complete');
  await p.fill('#q-millaje', '45k'); await p.tap('#q-title'); await settle(p);
  ok(await p.inputValue('#q-millaje') === '45' || (await txt(p, '#q-millaje-err')) !== '', 'mileage keeps numbers only', await p.inputValue('#q-millaje'));
  await p.fill('#q-millaje', '45,000'); await settle(p);
  ok(await txt(p, '#q-millaje-err') === '', 'mileage 45,000 accepted');
  await p.screenshot({ path: SHOT('1c-vehiculo-done') });
  // phone Back while a picker is open closes only the picker
  await p.tap('#q-vehiculo'); await settle(p);
  await p.goBack(); await settle(p);
  ok(!(await p.$('.sheet')) && await title() === '¿Qué auto quieres asegurar?', 'phone Back closes the picker, stays on the question');

  console.log('STEP 2 uso');
  await p.tap(primary); await settle(p);
  ok(await title() === '¿Cómo usas el auto?' && await count() === 'Paso 2 de 9', 'uso step 2/9');
  ok(await txt(p, '.q-context') === '2021 Honda CR-V', 'vehicle chip on later screens', await txt(p, '.q-context'));
  await p.tap('.q-help'); await settle(p);
  ok((await txt(p, '.sheet-text')).includes('Uber o Lyft'), 'help sheet explains the options');
  await p.screenshot({ path: SHOT('2b-help') });
  await p.tap('.sheet .q-primary'); await settle(p);
  ok(!(await p.$('.sheet')), 'help closes with Entendido');
  await p.goBack(); await settle(p);
  ok(await title() === '¿Qué auto quieres asegurar?' && await p.inputValue('#q-vin') === '1HGCM82633A004352', 'phone Back → previous question, answers kept');
  await p.goForward(); await settle(p);
  ok(await title() === '¿Cómo usas el auto?', 'Forward returns');
  await p.tap('label:has-text("Apps de trabajo")'); await settle(p);
  await p.screenshot({ path: SHOT('2-uso') });
  await p.tap(primary); await settle(p);

  console.log('STEP 3 propiedad');
  ok(await count() === 'Paso 3 de 9', 'propiedad 3/9');
  await p.tap('label:has-text("Lo estoy financiando")'); await p.tap(primary); await settle(p);

  console.log('STEP 4 inicio');
  ok(await title() === '¿Cuándo quieres que empiece tu seguro?' && await count() === 'Paso 4 de 9', 'inicio 4/9');
  ok(await p.isChecked('#q-inicio-0'), '"Hoy" preselected');
  ok((await txt(p, '.q-date-line')).startsWith('Tu seguro empezaría el'), 'date spelled out', await txt(p, '.q-date-line'));
  await p.tap('label[for="q-inicio-2"]'); await settle(p);
  ok(await p.isVisible('#q-inicio-date'), '"Otra fecha" reveals the date field');
  await p.fill('#q-inicio-date', '2020-01-01'); await p.tap(primary); await settle(p);
  ok((await txt(p, '#q-inicio-err')).includes('próximos 90 días'), 'past date refused', await txt(p, '#q-inicio-err'));
  const d10 = await p.evaluate(() => { const d = new Date(); d.setDate(d.getDate() + 10); return d.toISOString().slice(0, 10).replace(/(\d{4})-(\d\d)-(\d\d)/, (m, y, mo, da) => { const x = new Date(); x.setDate(x.getDate() + 10); return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`; }); });
  await p.fill('#q-inicio-date', d10); await settle(p);
  ok(await txt(p, '#q-inicio-err') === '', 'valid date accepted');
  await p.screenshot({ path: SHOT('4-inicio') });
  await p.tap(primary); await settle(p);

  console.log('STEP 5 cobertura');
  ok(await title() === '¿Qué cobertura buscas?', 'cobertura');
  await p.tap('label:has-text("Lo básico")'); await settle(p); await p.waitForTimeout(400);
  ok(await p.evaluate(() => { const r = document.querySelector('.q-note').getBoundingClientRect(); return r.bottom <= document.querySelector('.q-scroll').getBoundingClientRect().bottom + 1; }), 'note scrolled into view');
  ok((await txt(p, '.q-note')).includes('financiado, el banco normalmente exige cobertura completa'), 'financing note appears', await txt(p, '.q-note'));
  await p.screenshot({ path: SHOT('5-cobertura-note') });
  await p.tap(primary); await settle(p);

  console.log('STEP 6 seguro actual');
  ok(await count() === 'Paso 6 de 9', 'seguro actual 6/9');
  ok(!(await p.isVisible('#q-aseguradora')), 'company hidden until Sí');
  await p.tap('label[for="q-seguroActual-0"]'); await settle(p);
  ok(await p.isVisible('#q-aseguradora'), 'company appears after Sí');
  await p.fill('#q-aseguradora', 'GEICO');
  await p.screenshot({ path: SHOT('6-seguro') });
  await p.tap(primary); await settle(p);

  console.log('STEP 7 sobre ti');
  ok(await title() === 'Cuéntanos sobre ti', 'conductor');
  await p.tap(primary); await settle(p);
  const e7 = await p.$$eval('.q-error', n => n.map(x => x.textContent).filter(Boolean));
  ok(e7.length === 2 && !e7.some(x => x.includes('ZIP')), 'two required errors (ZIP already given on the intro)', e7);
  await p.selectOption('#q-dob-dobD', '30'); await p.selectOption('#q-dob-dobM', '2'); await p.selectOption('#q-dob-dobY', '1990'); await settle(p);
  ok((await txt(p, '#q-dob-err')).startsWith('Esa fecha no existe'), 'Feb 30 refused', await txt(p, '#q-dob-err'));
  await p.selectOption('#q-dob-dobD', '15'); await p.selectOption('#q-dob-dobM', '3'); await p.selectOption('#q-dob-dobY', '1989'); await settle(p);
  ok(await txt(p, '#q-dob-err') === '', 'valid birthday accepted');
  ok(await p.inputValue('#q-zip') === '33130' && !(await p.$('.q-zip-pill')), 'ZIP carried from the intro (no pill on this step)', await p.inputValue('#q-zip'));
  await p.fill('#q-zip', ''); await p.type('#q-zip', '33a1-25'); await settle(p);
  ok(await p.inputValue('#q-zip') === '33125', 'ZIP keeps digits only', await p.inputValue('#q-zip'));
  await p.tap('#q-accidentes-1 + label'); await settle(p);
  await p.screenshot({ path: SHOT('7-conductor') });
  await p.tap(primary); await settle(p);

  console.log('STEP 8 contacto');
  ok(await title() === 'Último paso: tus datos' && await count() === 'Paso 8 de 9', 'contacto 8/9');
  ok((await txt(p, '.q-privacy')).includes('solo a Best National Insurance'), 'privacy line');
  await p.fill('#q-nombre', 'María Pérez'); await p.fill('#q-email', 'maria@');
  await p.press('#q-email', 'Enter'); await settle(p);
  ok(await p.evaluate(() => document.activeElement.id) === 'q-telefono', 'keyboard Siguiente moves to the next box');
  await p.press('#q-telefono', 'Enter'); await settle(p);
  ok((await txt(p, '#q-email-err')) === 'Escribe un email válido.' && await title() === 'Último paso: tus datos', 'Enter on last box tries to continue; bad email blocks');
  await p.fill('#q-email', 'maria@example.com'); await settle(p);
  await p.screenshot({ path: SHOT('8-contacto') });
  await p.press('#q-email', 'Enter'); await p.press('#q-telefono', 'Enter'); await settle(p);

  console.log('STEP 9 resumen');
  ok(await title() === 'Revisa tu información' && await count() === 'Paso 9 de 9', 'review 9/9');
  const rows = await p.$$eval('.q-row', n => n.map(r => r.querySelector('.q-row-label').textContent + ': ' + r.querySelector('.q-row-value').textContent));
  console.log('    ' + rows.join('\n    '));
  ok(rows.includes('Auto: 2021 Honda CR-V') && rows.includes('Uso: Apps de trabajo (Uber, Lyft, entregas)') && rows.includes('Seguro actual: Sí, con GEICO') && rows.includes('Fecha de nacimiento: 15 de marzo de 1989'), 'review rows');
  ok(rows[rows.length - 5].startsWith('Nombre'), 'name leads the Tus datos card', rows[rows.length - 5]);
  await p.setViewportSize({ width: 390, height: 1500 }); await settle(p);
  await p.screenshot({ path: SHOT('9-resumen') });
  await p.setViewportSize({ width: 390, height: 664 }); await settle(p);
  const iSummary = (await state(p)).i;
  await p.tap('.q-row:has-text("Apps de trabajo")'); await settle(p);
  ok(await title() === '¿Cómo usas el auto?' && await txt(p, primary) === 'Guardar y volver', 'edit from review', await txt(p, primary));
  await p.tap('label:has-text("Personal")'); await p.tap(primary); await settle(p);
  ok(await title() === 'Revisa tu información' && (await state(p)).i === iSummary, 'Guardar y volver returns to the same review entry', await state(p));
  ok((await txt(p, '.q-card')).includes('Personal'), 'review updated');
  await p.tap('label[for="q-bundle"]');

  console.log('SEND');
  await p.tap(primary); await settle(p); await p.waitForTimeout(400);
  const waReqs = wa.filter(u => u.includes('wa.me'));
  ok(waReqs.length === 1, 'WhatsApp opened exactly once', waReqs.length);
  const msg = decode(waReqs[0]);
  console.log('    --- message ---\n' + msg.split('\n').map(l => '    ' + l).join('\n'));
  ok(waReqs[0].startsWith('https://wa.me/13054070139?text='), 'to 305-407-0139');
  ok(msg.startsWith('Hola Best National, soy María Pérez. Quiero una cotización de *seguro de auto*.'), 'personal greeting');
  ok(msg.includes('*Vehículo*\n• Auto: 2021 Honda CR-V\n• VIN: 1HGCM82633A004352\n• Millaje: 45,000 millas\n• Uso: Personal\n• Propiedad: Financiado'), 'vehicle section (with mileage)');
  ok(msg.includes('• Tipo: Lo básico (mínimo de Florida)') && msg.includes('• Seguro actual: Sí, con GEICO'), 'coverage section');
  ok(msg.includes('*Mis datos*\n• Fecha de nacimiento: 15 de marzo de 1989\n• ZIP: 33125\n• Accidentes o multas (3 años): No\n• Email: maria@example.com'), 'my details section');
  ok(!msg.includes('Nombre:'), 'name not repeated as a row');
  ok(msg.trim().endsWith('También me interesa cotizar el seguro de mi casa.'), 'bundle line');
  ok(await title() === '¡Listo! Te estamos conectando por WhatsApp…', 'confirmation screen');
  ok(await p.getAttribute('.q-done a.q-primary', 'href') === waReqs[0], 'fallback button has the same link');
  ok((await txt(p, '.q-recap')).includes('Seguro de auto · 2021 Honda CR-V'), 'recap');
  await p.screenshot({ path: SHOT('10-done') });
  await p.goBack(); await settle(p);
  ok(await title() === 'Revisa tu información', 'Back from confirmation shows the review');

  console.log('CLOSE');
  await p.tap('.q-bar .sheet-btn[aria-label="Cerrar"]'); await settle(p); await p.waitForTimeout(300);
  ok(!(await p.$('.q-flow')), 'flow closed');
  ok((await state(p)) === null, 'history back to the page entry', await state(p));
  ok(!(await p.evaluate(() => document.getElementById('content-app').inert)), 'page interactive again');
  ok(await p.evaluate(() => document.activeElement.dataset.form) === 'auto', 'focus back on the Cotiza button');
  await p.tap('.app-cta[data-form="auto"]'); await settle(p);
  ok(!(await p.isVisible('.q-secondary')) && await txt(p, primary) === 'Empezar', 'after sending, next quote starts fresh');
  await p.keyboard.press('Escape'); await settle(p); await p.waitForTimeout(300);
  ok(!(await p.$('.q-flow')), 'Escape closes the flow');
  ok(await p.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'no horizontal scroll');
  ok(errs.length === 0, 'no console errors', errs);
  await b.close();
  process.exit(summary() ? 1 : 0);
})().catch(e => { console.error(e); process.exit(2); });
